import { useMemo, useSyncExternalStore } from 'react';

const SUPPORTED_LANGUAGES = ['en', 'km', 'zh'];
const DEFAULT_LANGUAGE = 'en';
const APP_LANGUAGE_CHANGE_EVENT = 'app:language-change';
const LANGUAGE_CHANGE_FALLBACK_EVENT = 'languagechange';
const LANGUAGE_SUBSCRIBERS = new Set();
let SHARED_LANGUAGE = DEFAULT_LANGUAGE;
let LANGUAGE_LISTENERS_BOUND = false;

const TRANSLATIONS = {
  en: {
    'nav.discover': 'DISCOVER',
    'nav.news': 'News',
    'nav.video': 'Video',
    'nav.categories': 'Categories',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'auth.signIn': 'SIGN IN',
    'auth.logout': 'Logout',
    'search.open': 'Open search',
    'search.placeholder': 'Search news, topics, categories...',
    'search.button': 'Search',
    'search.close': 'Close',
    'search.quickJump': 'Quick Jump',
    'search.escToClose': 'Press Esc to close',
    'search.allNews': 'All News',
    'search.trendingTopics': 'Trending Topics',
    'footer.links': 'Links',
    'footer.company': 'Company',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.aboutUs': 'About Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'common.viewAll': 'View all',
    'common.seeMore': 'See more',
    'common.loadMore': 'Load more',
    'common.loading': 'Loading...',
    'common.loadingMore': 'Loading more...',
    'common.searching': 'Searching...',
    'common.clearSearch': 'Clear search',
    'common.clear': 'Clear',
    'common.backToNews': 'Back to News',
    'common.backToWebsite': 'Back to Website',
    'common.share': 'Share:',
    'common.copied': 'Copied',
    'common.more': 'More',
    'common.subscribe': 'Subscribe',
    'common.yourEmail': 'Your email',
    'common.stayUpdated': 'Stay Updated',
    'common.latestNewsInbox': 'Get the latest news delivered to your inbox.',
    'common.notFound': 'Page not found',
    'common.goHome': 'Go Home',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.continueWithFacebook': 'Continue with Facebook',
    'auth.orUseEmail': 'or use email',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signUp': 'Sign up',
    'auth.createAccount': 'Create Account',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.gender': 'Gender',
    'auth.birthday': 'Birthday',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.day': 'Day',
    'auth.month': 'Month',
    'auth.year': 'Year',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.passwordStrength': 'Password strength',
    'auth.weak': 'Weak',
    'auth.fair': 'Fair',
    'auth.good': 'Good',
    'auth.strong': 'Strong',
    'auth.veryStrong': 'Very Strong',
    'articles.newsFeed': 'News Feed',
    'articles.searchResults': 'Search Results',
    'articles.noNewsFound': 'No news found',
    'articles.results': '{{count}} results',
    'articles.resultsMore': '{{count}}+ results',
    'categories.browseByTopic': 'Browse by topic',
    'categories.topics': 'Topics',
    'categories.popular': 'Popular',
    'categories.showingOf': 'Showing {{shown}} of {{total}} categories',
    'categories.searchPlaceholder': 'Search categories (e.g., business, sports, tech)...',
  },
  km: {
    'nav.discover': 'ស្វែងរក',
    'nav.news': 'ព័ត៌មាន',
    'nav.video': 'វីដេអូ',
    'nav.categories': 'ប្រភេទ',
    'nav.about': 'អំពីយើង',
    'nav.contact': 'ទំនាក់ទំនង',
    'nav.dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'nav.profile': 'ប្រវត្តិរូប',
    'auth.signIn': 'ចូលគណនី',
    'auth.logout': 'ចាកចេញ',
    'search.open': 'បើកការស្វែងរក',
    'search.placeholder': 'ស្វែងរកព័ត៌មាន ប្រធានបទ ប្រភេទ...',
    'search.button': 'ស្វែងរក',
    'search.close': 'បិទ',
    'search.quickJump': 'ចូលលឿន',
    'search.escToClose': 'ចុច Esc ដើម្បីបិទ',
    'search.allNews': 'ព័ត៌មានទាំងអស់',
    'search.trendingTopics': 'ប្រធានបទពេញនិយម',
    'footer.links': 'តំណភ្ជាប់',
    'footer.company': 'ក្រុមហ៊ុន',
    'footer.resources': 'ធនធាន',
    'footer.legal': 'ច្បាប់',
    'footer.aboutUs': 'អំពីយើង',
    'footer.privacy': 'គោលការណ៍ឯកជនភាព',
    'footer.terms': 'លក្ខខណ្ឌប្រើប្រាស់',
    'common.viewAll': 'មើលទាំងអស់',
    'common.seeMore': 'មើលបន្ថែម',
    'common.loadMore': 'បង្ហាញបន្ថែម',
    'common.loading': 'កំពុងផ្ទុក...',
    'common.loadingMore': 'កំពុងផ្ទុកបន្ថែម...',
    'common.searching': 'កំពុងស្វែងរក...',
    'common.clearSearch': 'លុបការស្វែងរក',
    'common.clear': 'លុប',
    'common.backToNews': 'ត្រឡប់ទៅព័ត៌មាន',
    'common.backToWebsite': 'ត្រឡប់ទៅគេហទំព័រ',
    'common.share': 'ចែករំលែក៖',
    'common.copied': 'បានចម្លង',
    'common.more': 'បន្ថែម',
    'common.subscribe': 'ជាវ',
    'common.yourEmail': 'អ៊ីមែលរបស់អ្នក',
    'common.stayUpdated': 'ទទួលព័ត៌មានថ្មីៗ',
    'common.latestNewsInbox': 'ទទួលព័ត៌មានថ្មីៗបំផុតតាមអ៊ីមែលរបស់អ្នក។',
    'common.notFound': 'រកមិនឃើញទំព័រ',
    'common.goHome': 'ទៅទំព័រដើម',
    'auth.continueWithGoogle': 'បន្តជាមួយ Google',
    'auth.continueWithFacebook': 'បន្តជាមួយ Facebook',
    'auth.orUseEmail': 'ឬប្រើអ៊ីមែល',
    'auth.rememberMe': 'ចងចាំខ្ញុំ',
    'auth.forgotPassword': 'ភ្លេចពាក្យសម្ងាត់?',
    'auth.noAccount': 'មិនទាន់មានគណនីមែនទេ?',
    'auth.haveAccount': 'មានគណនីរួចហើយ?',
    'auth.signUp': 'ចុះឈ្មោះ',
    'auth.createAccount': 'បង្កើតគណនី',
    'auth.firstName': 'នាមខ្លួន',
    'auth.lastName': 'នាមត្រកូល',
    'auth.gender': 'ភេទ',
    'auth.birthday': 'ថ្ងៃខែឆ្នាំកំណើត',
    'auth.male': 'ប្រុស',
    'auth.female': 'ស្រី',
    'auth.day': 'ថ្ងៃ',
    'auth.month': 'ខែ',
    'auth.year': 'ឆ្នាំ',
    'auth.password': 'ពាក្យសម្ងាត់',
    'auth.confirmPassword': 'បញ្ជាក់ពាក្យសម្ងាត់',
    'auth.passwordStrength': 'កម្រិតពាក្យសម្ងាត់',
    'auth.weak': 'ខ្សោយ',
    'auth.fair': 'មធ្យម',
    'auth.good': 'ល្អ',
    'auth.strong': 'ខ្លាំង',
    'auth.veryStrong': 'ខ្លាំងណាស់',
    'articles.newsFeed': 'ព័ត៌មាន',
    'articles.searchResults': 'លទ្ធផលស្វែងរក',
    'articles.noNewsFound': 'រកមិនឃើញព័ត៌មាន',
    'articles.results': 'លទ្ធផល {{count}}',
    'articles.resultsMore': 'លទ្ធផល {{count}}+',
    'categories.browseByTopic': 'ស្វែងរកតាមប្រធានបទ',
    'categories.topics': 'ប្រធានបទ',
    'categories.popular': 'ពេញនិយម',
    'categories.showingOf': 'បង្ហាញ {{shown}} ក្នុងចំណោម {{total}} ប្រភេទ',
    'categories.searchPlaceholder': 'ស្វែងរកប្រភេទ (ឧ. ពាណិជ្ជកម្ម កីឡា បច្ចេកវិទ្យា)...',
  },
  zh: {
    'nav.discover': '发现',
    'nav.news': '新闻',
    'nav.video': '视频',
    'nav.categories': '分类',
    'nav.about': '关于',
    'nav.contact': '联系',
    'nav.dashboard': '仪表盘',
    'nav.profile': '个人资料',
    'auth.signIn': '登录',
    'auth.logout': '退出登录',
    'search.open': '打开搜索',
    'search.placeholder': '搜索新闻、主题、分类...',
    'search.button': '搜索',
    'search.close': '关闭',
    'search.quickJump': '快速跳转',
    'search.escToClose': '按 Esc 关闭',
    'search.allNews': '全部新闻',
    'search.trendingTopics': '热门话题',
    'footer.links': '链接',
    'footer.company': '公司',
    'footer.resources': '资源',
    'footer.legal': '法律',
    'footer.aboutUs': '关于我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'common.viewAll': '查看全部',
    'common.seeMore': '查看更多',
    'common.loadMore': '加载更多',
    'common.loading': '加载中...',
    'common.loadingMore': '正在加载更多...',
    'common.searching': '搜索中...',
    'common.clearSearch': '清除搜索',
    'common.clear': '清除',
    'common.backToNews': '返回新闻',
    'common.backToWebsite': '返回网站',
    'common.share': '分享：',
    'common.copied': '已复制',
    'common.more': '更多',
    'common.subscribe': '订阅',
    'common.yourEmail': '你的邮箱',
    'common.stayUpdated': '保持更新',
    'common.latestNewsInbox': '将最新新闻发送到你的邮箱。',
    'common.notFound': '页面未找到',
    'common.goHome': '返回首页',
    'auth.continueWithGoogle': '使用 Google 继续',
    'auth.continueWithFacebook': '使用 Facebook 继续',
    'auth.orUseEmail': '或使用邮箱',
    'auth.rememberMe': '记住我',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '还没有账号？',
    'auth.haveAccount': '已有账号？',
    'auth.signUp': '注册',
    'auth.createAccount': '创建账号',
    'auth.firstName': '名字',
    'auth.lastName': '姓氏',
    'auth.gender': '性别',
    'auth.birthday': '生日',
    'auth.male': '男',
    'auth.female': '女',
    'auth.day': '日',
    'auth.month': '月',
    'auth.year': '年',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.passwordStrength': '密码强度',
    'auth.weak': '弱',
    'auth.fair': '一般',
    'auth.good': '良好',
    'auth.strong': '强',
    'auth.veryStrong': '非常强',
    'articles.newsFeed': '新闻动态',
    'articles.searchResults': '搜索结果',
    'articles.noNewsFound': '未找到新闻',
    'articles.results': '{{count}} 条结果',
    'articles.resultsMore': '{{count}}+ 条结果',
    'categories.browseByTopic': '按主题浏览',
    'categories.topics': '主题',
    'categories.popular': '热门',
    'categories.showingOf': '显示 {{shown}} / {{total}} 个分类',
    'categories.searchPlaceholder': '搜索分类（例如：商业、体育、科技）...',
  },
};

const PHRASE_TRANSLATIONS = {
  km: {
    'featured': 'លេចធ្លោ',
    'highlight': 'ចំណុចសំខាន់',
    'more featured': 'លេចធ្លោបន្ថែម',
    'breaking': 'ព័ត៌មានបន្ទាន់',
    'alert': 'ជូនដំណឹង',
    'latest': 'ថ្មីបំផុត',
    'trending': 'កំពុងពេញនិយម',
    'news': 'ព័ត៌មាន',
    'categories': 'ប្រភេទ',
    'stories': 'រឿងរ៉ាវ',
    'magazine': 'ទស្សនាវដ្តី',
    'editors': 'ក្រុមនិពន្ធ',
    'spotlight': 'ចំណុចពិសេស',
    'quick update': 'ព័ត៌មានរហ័ស',
    'stay updated': 'ទទួលព័ត៌មានថ្មីៗ',
    'fresh headlines drop every hour. stay ahead with real-time coverage.': 'ចំណងជើងថ្មីៗអាប់ដេតរៀងរាល់ម៉ោង។ តាមដានព័ត៌មានទាន់ពេលវេលា។',
    'no news available': 'មិនមានព័ត៌មាន',
    'no featured news. mark news as featured in the dashboard.': 'មិនមានព័ត៌មានលេចធ្លោ។ សូមកំណត់ព័ត៌មានលេចធ្លោក្នុងផ្ទាំងគ្រប់គ្រង។',
    'no additional featured news available.': 'មិនមានព័ត៌មានលេចធ្លោបន្ថែម។',
    'no breaking news in the dashboard.': 'មិនមានព័ត៌មានបន្ទាន់ក្នុងផ្ទាំងគ្រប់គ្រង។',
    'no breaking news yet': 'មិនទាន់មានព័ត៌មានបន្ទាន់',
    'no news published yet': 'មិនទាន់មានព័ត៌មានបានបោះពុម្ព',
    'no trending news': 'មិនមានព័ត៌មានកំពុងពេញនិយម',
    'no editor picks available': 'មិនមានជម្រើសពីអ្នកនិពន្ធ',
    'no news in this category yet': 'មិនទាន់មានព័ត៌មានក្នុងប្រភេទនេះ',
    'category': 'ប្រភេទ',
    'power, policy, and people shaping the week.': 'ថាមពល គោលនយោបាយ និងមនុស្សដែលកំពុងបង្កើតសប្ដាហ៍នេះ។',
    'more': 'បន្ថែម',
    'view all': 'មើលទាំងអស់',
    'see more': 'មើលបន្ថែម',
    'all news': 'ព័ត៌មានទាំងអស់',
    'browse news': 'មើលព័ត៌មាន',
    'search results': 'លទ្ធផលស្វែងរក',
    'search posts, topics, authors...': 'ស្វែងរកប្រកាស ប្រធានបទ អ្នកនិពន្ធ...',
    'news feed': 'ព័ត៌មាន',
    'find stories faster with search and category filters.': 'ស្វែងរកព័ត៌មានបានលឿនជាមួយការស្វែងរក និងតម្រងប្រភេទ។',
    'loading more...': 'កំពុងផ្ទុកបន្ថែម...',
    'load more': 'បង្ហាញបន្ថែម',
    'no news found': 'រកមិនឃើញព័ត៌មាន',
    'clear search': 'លុបការស្វែងរក',
    'browse by topic': 'ស្វែងរកតាមប្រធានបទ',
    'all news': 'ព័ត៌មានទាំងអស់',
    'topics': 'ប្រធានបទ',
    'popular': 'ពេញនិយម',
    'clear': 'លុប',
    'no categories found': 'រកមិនឃើញប្រភេទ',
    'try a different search, or browse all news.': 'សាកល្បងស្វែងរកផ្សេង ឬមើលព័ត៌មានទាំងអស់។',
    'topic page': 'ទំព័រប្រធានបទ',
    'explore': 'ស្វែងយល់',
    'back to news': 'ត្រឡប់ទៅព័ត៌មាន',
    'share:': 'ចែករំលែក៖',
    'copied': 'បានចម្លង',
    'more news': 'ព័ត៌មានបន្ថែម',
    'related news': 'ព័ត៌មានពាក់ព័ន្ធ',
    'no related news found': 'រកមិនឃើញព័ត៌មានពាក់ព័ន្ធ',
    'no additional news available': 'មិនមានព័ត៌មានបន្ថែម',
    'comments': 'មតិយោបល់',
    'reply': 'ឆ្លើយតប',
    'cancel': 'បោះបង់',
    'write a reply...': 'សរសេរការឆ្លើយតប...',
    'your name': 'ឈ្មោះរបស់អ្នក',
    'your email': 'អ៊ីមែលរបស់អ្នក',
    'share your thoughts...': 'ចែករំលែកគំនិតរបស់អ្នក...',
    'write a comment...': 'សរសេរមតិយោបល់...',
    'your name *': 'ឈ្មោះរបស់អ្នក *',
    'your email *': 'អ៊ីមែលរបស់អ្នក *',
    'comments are moderated before appearing': 'មតិយោបល់នឹងត្រូវបានពិនិត្យមុនបង្ហាញ',
    'posting...': 'កំពុងបង្ហោះ...',
    'post comment': 'បង្ហោះមតិយោបល់',
    'no comments yet. be the first to share your thoughts!': 'មិនទាន់មានមតិយោបល់។ អ្នកអាចជាមនុស្សដំបូងដែលចែករំលែកគំនិត!',
    'load more comments': 'បង្ហាញមតិយោបល់បន្ថែម',
    'delete comment': 'លុបមតិយោបល់',
    'are you sure you want to delete this comment?': 'តើអ្នកប្រាកដថាចង់លុបមតិយោបល់នេះទេ?',
    'delete': 'លុប',
    'news not found': 'រកមិនឃើញព័ត៌មាន',
    "the news you're looking for doesn't exist.": 'ព័ត៌មានដែលអ្នកកំពុងស្វែងរកមិនមានទេ។',
    'sign in': 'ចូលគណនី',
    'continue with google': 'បន្តជាមួយ Google',
    'continue with facebook': 'បន្តជាមួយ Facebook',
    'or use email': 'ឬប្រើអ៊ីមែល',
    'email': 'អ៊ីមែល',
    'password': 'ពាក្យសម្ងាត់',
    'remember me': 'ចងចាំខ្ញុំ',
    'forgot password?': 'ភ្លេចពាក្យសម្ងាត់?',
    "don't have an account?": 'មិនទាន់មានគណនីមែនទេ?',
    'sign up': 'ចុះឈ្មោះ',
    'demo accounts:': 'គណនីសាកល្បង៖',
    'create account': 'បង្កើតគណនី',
    'first name': 'នាមខ្លួន',
    'last name': 'នាមត្រកូល',
    'gender': 'ភេទ',
    'birthday': 'ថ្ងៃខែឆ្នាំកំណើត',
    'day': 'ថ្ងៃ',
    'month': 'ខែ',
    'year': 'ឆ្នាំ',
    'confirm password': 'បញ្ជាក់ពាក្យសម្ងាត់',
    'already have an account?': 'មានគណនីរួចហើយ?',
    'checking email availability...': 'កំពុងពិនិត្យអ៊ីមែល...',
    'email is available': 'អ៊ីមែលអាចប្រើបាន',
    'could not verify email right now': 'មិនអាចពិនិត្យអ៊ីមែលឥឡូវនេះ',
    'password strength:': 'កម្រិតពាក្យសម្ងាត់៖',
    'weak': 'ខ្សោយ',
    'fair': 'មធ្យម',
    'good': 'ល្អ',
    'strong': 'ខ្លាំង',
    'very strong': 'ខ្លាំងណាស់',
    'complete your profile': 'បំពេញប្រវត្តិរូបរបស់អ្នក',
    'we need your gender and birthday to finish your account setup.': 'យើងត្រូវការភេទ និងថ្ងៃខែឆ្នាំកំណើត ដើម្បីបញ្ចប់ការកំណត់គណនី។',
    'select gender': 'ជ្រើសរើសភេទ',
    'save & continue': 'រក្សាទុក និងបន្ត',
    'account': 'គណនី',
    'edit profile': 'កែប្រែប្រវត្តិរូប',
    'bio': 'ប្រវត្តិខ្លី',
    'tell us about yourself...': 'ប្រាប់អំពីខ្លួនអ្នក...',
    'save changes': 'រក្សាទុកការផ្លាស់ប្តូរ',
    'tap the camera icon to choose, crop, and update your photo.': 'ចុចរូបកាមេរ៉ា ដើម្បីជ្រើស កាត់ និងអាប់ដេតរូបថត។',
    'edit profile picture': 'កែសម្រួលរូបប្រវត្តិ',
    'drag image to reposition inside the circle': 'អូសរូបភាព ដើម្បីកំណត់ទីតាំងក្នុងរង្វង់',
    'zoom': 'ពង្រីក',
    'rotation': 'បង្វិល',
    'reset': 'កំណត់ឡើងវិញ',
    'done & update': 'រួចរាល់ និងអាប់ដេត',
    'processing...': 'កំពុងដំណើរការ...',
    'confirm action': 'បញ្ជាក់សកម្មភាព',
    'are you sure you want to proceed?': 'តើអ្នកប្រាកដថាចង់បន្តទេ?',
    'confirm': 'បញ្ជាក់',
    'alert': 'ជូនដំណឹង',
    'ok': 'យល់ព្រម',
    'advertisement': 'ពាណិជ្ជកម្ម',
    'ad': 'ផ្សាយពាណិជ្ជកម្ម',
    'back to website': 'ត្រឡប់ទៅគេហទំព័រ',
    'page not found': 'រកមិនឃើញទំព័រ',
    'go home': 'ទៅទំព័រដើម',
    'section': 'ផ្នែក',
    'breaking news': 'ព័ត៌មានបន្ទាន់',
    'latest news': 'ព័ត៌មានថ្មីៗ',
    'latest alerts and urgent updates': 'ការជូនដំណឹងថ្មីៗ និងបច្ចុប្បន្នភាពបន្ទាន់',
    'view all news': 'មើលព័ត៌មានទាំងអស់',
    'uncategorized': 'មិនទាន់ចាត់ប្រភេទ',
    'admin': 'អ្នកគ្រប់គ្រង',
    'anonymous': 'អនាមិក',
    'edited': 'បានកែសម្រួល',
    'approved': 'បានអនុម័ត',
    'views': 'ដងមើល',
    'close ad': 'បិទផ្សាយពាណិជ្ជកម្ម',
    'find stories faster with topic pages—search, sort, and jump into what you care about.': 'ស្វែងរកព័ត៌មានបានលឿនតាមទំព័រប្រធានបទ ដោយស្វែងរក តម្រៀប និងចូលទៅអ្វីដែលអ្នកចាប់អារម្មណ៍។',
    'explore the latest updates in': 'ស្វែងយល់ព័ត៌មានថ្មីៗក្នុង',
    'view': 'មើល',
    'more stories': 'រឿងរ៉ាវបន្ថែម',
    'latest news & updates': 'ព័ត៌មាន និងបច្ចុប្បន្នភាពថ្មីៗ',
    'required': 'ត្រូវបំពេញ',
    'email is required': 'ត្រូវការអ៊ីមែល',
    'password is required': 'ត្រូវការពាក្យសម្ងាត់',
    'invalid email address': 'អាសយដ្ឋានអ៊ីមែលមិនត្រឹមត្រូវ',
    'invalid gender': 'ភេទមិនត្រឹមត្រូវ',
    'birthday is required': 'ត្រូវការថ្ងៃខែឆ្នាំកំណើត',
    'birthday is invalid': 'ថ្ងៃខែឆ្នាំកំណើតមិនត្រឹមត្រូវ',
    'birthday cannot be in the future': 'ថ្ងៃខែឆ្នាំកំណើតមិនអាចនៅអនាគត',
    'min 8 characters': 'យ៉ាងតិច 8 តួអក្សរ',
    'must include letters and numbers': 'ត្រូវមានអក្សរ និងលេខ',
    'passwords do not match': 'ពាក្យសម្ងាត់មិនដូចគ្នា',
    'email already registered': 'អ៊ីមែលនេះបានចុះឈ្មោះរួចហើយ',
    'please select your gender': 'សូមជ្រើសរើសភេទ',
    'please select your birthday': 'សូមជ្រើសរើសថ្ងៃខែឆ្នាំកំណើត',
    'please complete the required profile fields.': 'សូមបំពេញព័ត៌មានប្រវត្តិរូបដែលត្រូវការ។',
    'please select an image file': 'សូមជ្រើសរើសឯកសាររូបភាព',
    'image must be less than 5mb': 'រូបភាពត្រូវតែតូចជាង 5MB',
    'could not read this image': 'មិនអាចអានរូបភាពនេះបាន',
    'profile picture updated!': 'បានអាប់ដេតរូបប្រវត្តិរូប!',
    'upload failed': 'ការផ្ទុកឡើងបរាជ័យ',
    'about us': 'អំពីយើង',
    'an unexpected error occurred. please try again or go back to the home page.': 'មានកំហុសមិនរំពឹងទុកកើតឡើង។ សូមព្យាយាមម្តងទៀត ឬត្រឡប់ទៅទំព័រដើម។',
    'back to login': 'ត្រឡប់ទៅចូលគណនី',
    'back to pending': 'ត្រឡប់ទៅកាន់បញ្ជីរង់ចាំ',
    'balanced coverage that avoids sensational framing.': 'ការគ្របដណ្តប់មានតុល្យភាព ដែលជៀសវាងការរំភើបហួសហេតុ។',
    'browse categories': 'រកមើលប្រភេទ',
    'building trust through clear, independent journalism.': 'កសាងទំនុកចិត្តតាមរយៈសារព័ត៌មានឯករាជ្យច្បាស់លាស់។',
    'close preview': 'បិទការមើលជាមុន',
    'complete profile': 'បំពេញប្រវត្តិរូប',
    'confirm subscription': 'បញ្ជាក់ការជាវ',
    'confirmation failed': 'ការបញ្ជាក់បរាជ័យ',
    'confirming subscription': 'កំពុងបញ្ជាក់ការជាវ',
    'connect with': 'ភ្ជាប់ជាមួយ',
    'contact': 'ទំនាក់ទំនង',
    'contact team': 'ទាក់ទងក្រុមការងារ',
    'contact us': 'ទាក់ទងមកយើង',
    'continuous updates when facts evolve.': 'ធ្វើបច្ចុប្បន្នភាពបន្តបន្ទាប់ នៅពេលព័ត៌មានផ្លាស់ប្តូរ។',
    'coverage': 'ការគ្របដណ្តប់',
    'draft': 'ព្រាង',
    'editor': 'អ្នកកែសម្រួល',
    'email address': 'អាសយដ្ឋានអ៊ីមែល',
    'email verified!': 'អ៊ីមែលបានផ្ទៀងផ្ទាត់!',
    'enable browser notifications': 'បើកការជូនដំណឹងក្នុងកម្មវិធីរុករក',
    'enter your new password below.': 'បញ្ចូលពាក្យសម្ងាត់ថ្មីរបស់អ្នកខាងក្រោម។',
    'explore news': 'ស្វែងរកព័ត៌មាន',
    'fact-checked stories with clear sources and context.': 'ព័ត៌មានដែលបានពិនិត្យការពិត ជាមួយប្រភព និងបរិបទច្បាស់លាស់។',
    'failed to load': 'ផ្ទុកបរាជ័យ',
    'female': 'ស្រី',
    'follow our reporting and be part of the conversation.': 'តាមដានការរាយការណ៍របស់យើង ហើយចូលរួមការសន្ទនា។',
    'forgot password': 'ភ្លេចពាក្យសម្ងាត់',
    'from our newsroom': 'ពីបន្ទប់ព័ត៌មានរបស់យើង',
    'go to login': 'ទៅកាន់ការចូលគណនី',
    'independent': 'ឯករាជ្យ',
    'inform clearly. explain deeply. serve the public.': 'ជូនព័ត៌មានឱ្យច្បាស់។ ពន្យល់ឱ្យជ្រាលជ្រៅ។ បម្រើសាធារណៈ។',
    'invalid link': 'តំណមិនត្រឹមត្រូវ',
    'join our community': 'ចូលរួមសហគមន៍របស់យើង',
    'male': 'ប្រុស',
    'mark all read': 'សម្គាល់ថាអានទាំងអស់',
    'min': 'នាទី',
    'new': 'ថ្មី',
    'new password': 'ពាក្យសម្ងាត់ថ្មី',
    'newsroom workflow': 'ដំណើរការបន្ទប់ព័ត៌មាន',
    'no notifications yet': 'មិនទាន់មានការជូនដំណឹង',
    'no recent stories available right now.': 'បច្ចុប្បន្នមិនមានព័ត៌មានថ្មីៗទេ។',
    'notifications': 'ការជូនដំណឹង',
    'oops! something went wrong': 'អូហ៍! មានបញ្ហាមួយកើតឡើង',
    'our mission': 'បេសកកម្មរបស់យើង',
    'password reset!': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញរួចរាល់!',
    'phnom penh, cambodia': 'ភ្នំពេញ ប្រទេសកម្ពុជា',
    'please wait while we confirm your subscription...': 'សូមរង់ចាំ ខណៈពេលយើងបញ្ជាក់ការជាវរបស់អ្នក...',
    'please wait while we update your subscription...': 'សូមរង់ចាំ ខណៈពេលយើងធ្វើបច្ចុប្បន្នភាពការជាវរបស់អ្នក...',
    'please wait while we verify your email address...': 'សូមរង់ចាំ ខណៈពេលយើងផ្ទៀងផ្ទាត់អាសយដ្ឋានអ៊ីមែលរបស់អ្នក...',
    'preview': 'មើលជាមុន',
    'preview error': 'កំហុសក្នុងការមើលជាមុន',
    'preview mode': 'របៀបមើលជាមុន',
    'preview mode - this is how your news will look when published': 'របៀបមើលជាមុន - នេះគឺជារបៀបដែលព័ត៌មានរបស់អ្នកនឹងបង្ហាញនៅពេលបោះពុម្ព',
    'processing': 'កំពុងដំណើរការ',
    'redirecting to login...': 'កំពុងបញ្ជូនទៅទំព័រចូលគណនី...',
    'remember your password?': 'ចាំពាក្យសម្ងាត់របស់អ្នកទេ?',
    'request new link': 'ស្នើតំណថ្មី',
    'reset password': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
    'resetting...': 'កំពុងកំណត់ឡើងវិញ...',
    'send message': 'ផ្ញើសារ',
    'send reset link': 'ផ្ញើតំណកំណត់ឡើងវិញ',
    'send us a message': 'ផ្ញើសារមកយើង',
    'sending...': 'កំពុងផ្ញើ...',
    'sign-in failed': 'ការចូលគណនីបរាជ័យ',
    'signing you in': 'កំពុងចូលគណនីឱ្យអ្នក',
    'something went wrong': 'មានបញ្ហាមួយកើតឡើង',
    'stay updated with our latest investigations, explainers, and local stories that shape public dialogue.': 'ទទួលព័ត៌មានថ្មីៗពីការស៊ើបអង្កេត ការពន្យល់ និងរឿងរ៉ាវមូលដ្ឋានដែលប៉ះពាល់ដល់សាធារណៈ។',
    'step': 'ជំហាន',
    'subscribed!': 'បានជាវហើយ!',
    'this news is not available for preview.': 'ព័ត៌មាននេះមិនអាចមើលជាមុនបានទេ។',
    'to make journalism more useful for everyday readers. our newsroom focuses on verified reporting, practical context, and responsible storytelling that values people over noise.': 'ដើម្បីធ្វើឱ្យសារព័ត៌មានមានប្រយោជន៍ជាងមុនសម្រាប់អ្នកអានរាល់ថ្ងៃ។ បន្ទប់ព័ត៌មានរបស់យើងផ្តោតលើការរាយការណ៍ដែលបានផ្ទៀងផ្ទាត់ បរិបទអនុវត្តបាន និងការនិទានរឿងប្រកបដោយការទទួលខុសត្រូវ។',
    'try again': 'សាកល្បងម្ដងទៀត',
    'unsubscribe': 'បោះបង់ការជាវ',
    'unsubscribe failed': 'បោះបង់ការជាវបរាជ័យ',
    'unsubscribed': 'បានបោះបង់ការជាវ',
    'untitled': 'គ្មានចំណងជើង',
    'untitled news': 'ព័ត៌មានគ្មានចំណងជើង',
    'updates': 'បច្ចុប្បន្នភាព',
    'verification failed': 'ការផ្ទៀងផ្ទាត់បរាជ័យ',
    'verify email': 'ផ្ទៀងផ្ទាត់អ៊ីមែល',
    'verifying email': 'កំពុងផ្ទៀងផ្ទាត់អ៊ីមែល',
    'view all notifications': 'មើលការជូនដំណឹងទាំងអស់',
    'we created': 'យើងបានបង្កើត',
    'what we cover': 'អ្វីដែលយើងគ្របដណ្តប់',
    'writer': 'អ្នកនិពន្ធ',
    'english': 'អង់គ្លេស',
    'khmer': 'ខ្មែរ',
    'chinese': 'ចិន',
    'your trusted source for quality news, insightful stories, and in-depth coverage of the issues that matter.': 'ប្រភពព័ត៌មានដែលអ្នកទុកចិត្តសម្រាប់ព័ត៌មានគុណភាព រឿងរ៉ាវជ្រាលជ្រៅ និងការគ្របដណ្តប់លម្អិតលើប្រធានបទសំខាន់ៗ។',
    'your trusted source for quality news, insightful articles, and in-depth coverage of the stories that matter.': 'ប្រភពព័ត៌មានដែលអ្នកទុកចិត្តសម្រាប់ព័ត៌មានគុណភាព អត្ថបទជ្រាលជ្រៅ និងការគ្របដណ្តប់លម្អិតលើរឿងរ៉ាវសំខាន់ៗ។',
    'select language': 'ជ្រើសរើសភាសា',
    'avatar': 'រូបតំណាង',
    "have a question? we'd love to hear from you.": 'មានសំណួរមែនទេ? យើងរីករាយក្នុងការស្តាប់ពីអ្នក។',
    "enter your email and we'll send you a reset link.": 'បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើតំណកំណត់ឡើងវិញ។',
    'open': 'បើក',
    'pending': 'កំពុងរង់ចាំ',
    'no news in this category': 'មិនមានព័ត៌មានក្នុងប្រភេទនេះ',
    'this article is not available in the selected language yet. showing english version.': 'អត្ថបទនេះមិនទាន់មាននៅក្នុងភាសាដែលបានជ្រើសរើសទេ។ កំពុងបង្ហាញកំណែភាសាអង់គ្លេស។',
    "we're sorry, but something unexpected happened. our team has been notified.": 'សូមអភ័យទោស មានបញ្ហាមិនរំពឹងទុកកើតឡើង។ ក្រុមការងារយើងត្រូវបានជូនដំណឹងរួចហើយ។',
    '© {year} {sitename}. all rights reserved.': '© {year} {siteName}។ រក្សាសិទ្ធិគ្រប់យ៉ាង។',
    'all rights reserved.': 'រក្សាសិទ្ធិគ្រប់យ៉ាង។',
    'social sign-in failed. please try again.': 'ការចូលគណនីតាមបណ្តាញសង្គមបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
    'missing social login session. please try again.': 'បាត់សម័យចូលគណនីសង្គម។ សូមព្យាយាមម្តងទៀត។',
    'could not complete social sign-in. please try again.': 'មិនអាចបញ្ចប់ការចូលគណនីសង្គមបានទេ។ សូមព្យាយាមម្តងទៀត។',
    'invalid verification link. please request a new verification email.': 'តំណផ្ទៀងផ្ទាត់មិនត្រឹមត្រូវ។ សូមស្នើអ៊ីមែលផ្ទៀងផ្ទាត់ថ្មី។',
    'your email has been verified successfully!': 'អ៊ីមែលរបស់អ្នកបានផ្ទៀងផ្ទាត់ដោយជោគជ័យ!',
    'verification failed. the link may have expired.': 'ការផ្ទៀងផ្ទាត់បរាជ័យ។ តំណអាចផុតកំណត់ហើយ។',
    'an error occurred. please try again later.': 'មានកំហុសកើតឡើង។ សូមព្យាយាមម្ដងទៀតពេលក្រោយ។',
    'invalid confirmation link. please subscribe again.': 'តំណបញ្ជាក់មិនត្រឹមត្រូវ។ សូមជាវម្ដងទៀត។',
    'your subscription has been confirmed!': 'ការជាវរបស់អ្នកត្រូវបានបញ្ជាក់ហើយ!',
    'confirmation failed. the link may have expired.': 'ការបញ្ជាក់បរាជ័យ។ តំណអាចផុតកំណត់ហើយ។',
    'invalid unsubscribe link.': 'តំណបោះបង់ការជាវមិនត្រឹមត្រូវ។',
    'you have been unsubscribed successfully.': 'អ្នកបានបោះបង់ការជាវដោយជោគជ័យ។',
    'unsubscribe failed. please try again later.': 'ការបោះបង់ការជាវបរាជ័យ។ សូមព្យាយាមម្ដងទៀតពេលក្រោយ។',
    'if an account exists with this email, you will receive a password reset link.': 'បើមានគណនីជាមួយអ៊ីមែលនេះ អ្នកនឹងទទួលបានតំណកំណត់ពាក្យសម្ងាត់ឡើងវិញ។',
    'something went wrong. please try again.': 'មានបញ្ហាមួយកើតឡើង។ សូមព្យាយាមម្ដងទៀត។',
    'invalid reset link. please request a new password reset.': 'តំណកំណត់ពាក្យសម្ងាត់ឡើងវិញមិនត្រឹមត្រូវ។ សូមស្នើតំណថ្មី។',
    'passwords do not match.': 'ពាក្យសម្ងាត់មិនដូចគ្នា។',
    'password must be at least 8 characters.': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច 8 តួអក្សរ។',
    'your password has been reset successfully!': 'ពាក្យសម្ងាត់របស់អ្នកត្រូវបានកំណត់ឡើងវិញដោយជោគជ័យ!',
    'reset failed. the link may have expired.': 'ការកំណត់ឡើងវិញបរាជ័យ។ តំណអាចផុតកំណត់ហើយ។',
    'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'activity': 'សកម្មភាព',
    'welcome back,': 'សូមស្វាគមន៍ត្រឡប់មកវិញ,',
    'track newsroom momentum and stay ahead.': 'តាមដានចលនាបន្ទប់ព័ត៌មាន និងនាំមុខជានិច្ច។',
    'last 7 days': '៧ ថ្ងៃចុងក្រោយ',
    'last 30 days of traffic': 'ចរាចរណ៍ ៣០ ថ្ងៃចុងក្រោយ',
    'items': 'ធាតុ',
    'total views': 'ចំនួនមើលសរុប',
    'views over time': 'ចំនួនមើលតាមពេលវេលា',
    'published per day': 'បានបោះពុម្ពក្នុងមួយថ្ងៃ',
    'editorial output pace': 'ល្បឿនផលិតកម្មនិពន្ធ',
    'status mix': 'សមាសភាពស្ថានភាព',
    'published vs pending vs draft': 'បានបោះពុម្ព ប្រៀបនឹង រង់ចាំ និងព្រាង',
    'category performance': 'ប្រសិទ្ធភាពប្រភេទ',
    'views by category': 'ចំនួនមើលតាមប្រភេទ',
    'no category data yet': 'មិនទាន់មានទិន្នន័យប្រភេទ',
    'ad reach & ctr': 'ការឈានដល់ការផ្សាយពាណិជ្ជកម្ម និង CTR',
    'impressions vs clicks (last 30 days)': 'ការបង្ហាញ ប្រៀបនឹង ការចុច (៣០ ថ្ងៃចុងក្រោយ)',
    'total ctr': 'CTR សរុប',
    'impressions': 'ការបង្ហាញ',
    'clicks': 'ការចុច',
    'content momentum': 'ចលនាមាតិកា',
    'top stories': 'រឿងរ៉ាវពេញនិយម',
    'no top news yet': 'មិនទាន់មានព័ត៌មានពេញនិយម',
    'recent news': 'ព័ត៌មានថ្មីៗ',
    'no recent news': 'មិនមានព័ត៌មានថ្មីៗ',
    'quick actions': 'សកម្មភាពរហ័ស',
    'write new news': 'សរសេរព័ត៌មានថ្មី',
    'view my news': 'មើលព័ត៌មានរបស់ខ្ញុំ',
    'review pending news': 'ពិនិត្យព័ត៌មានកំពុងរង់ចាំ',
    'ad insights': 'ការយល់ដឹងពីការផ្សាយពាណិជ្ជកម្ម',
    'news insights': 'ការយល់ដឹងពីព័ត៌មាន',
    'all statuses': 'ស្ថានភាពទាំងអស់',
    'title': 'ចំណងជើង',
    'author': 'អ្នកនិពន្ធ',
    'date': 'កាលបរិច្ឆេទ',
    'view news': 'មើលព័ត៌មាន',
    'insights': 'ការយល់ដឹង',
    'unknown': 'មិនស្គាល់',
    'page': 'ទំព័រ',
    'of': 'នៃ',
    'previous': 'មុន',
    'next': 'បន្ទាប់',
    'no news yet': 'មិនទាន់មានព័ត៌មាន',
    'try adjusting your filters or create the first news item.': 'សាកល្បងកែតម្រូវតម្រង ឬបង្កើតព័ត៌មានដំបូង។',
    'start writing your first news item.': 'ចាប់ផ្តើមសរសេរព័ត៌មានដំបូងរបស់អ្នក។',
    'delete news': 'លុបព័ត៌មាន',
    'are you sure you want to delete this news? this action cannot be undone.': 'តើអ្នកប្រាកដថាចង់លុបព័ត៌មាននេះទេ? សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយបានទេ។',
    'pending news': 'ព័ត៌មានកំពុងរង់ចាំ',
    'pending review': 'កំពុងរង់ចាំពិនិត្យ',
    'news awaiting your approval': 'ព័ត៌មានកំពុងរង់ចាំការអនុម័តរបស់អ្នក',
    'by': 'ដោយ',
    'approve': 'អនុម័ត',
    'reject': 'បដិសេធ',
    'all caught up!': 'បានពិនិត្យគ្រប់ហើយ!',
    'no news pending review': 'មិនមានព័ត៌មានរង់ចាំពិនិត្យ',
    'approve news': 'អនុម័តព័ត៌មាន',
    'are you sure you want to approve this news for publication?': 'តើអ្នកប្រាកដថាចង់អនុម័តព័ត៌មាននេះសម្រាប់បោះពុម្ពផ្សាយទេ?',
    'reject news': 'បដិសេធព័ត៌មាន',
    'rejection reason': 'ហេតុផលបដិសេធ',
    'enter reason for rejection...': 'បញ្ចូលហេតុផលសម្រាប់ការបដិសេធ...',
    'please provide a reason for rejection': 'សូមផ្តល់ហេតុផលសម្រាប់ការបដិសេធ',
    'validation error': 'កំហុសផ្ទៀងផ្ទាត់',
    'profile': 'ប្រវត្តិរូប',
    'no data': 'មិនមានទិន្នន័យ',
    'no data available': 'មិនមានទិន្នន័យអាចប្រើបាន',
    'archived': 'បានរក្សាទុក',
    'new news': 'ព័ត៌មានថ្មី',
    'published': 'បានបោះពុម្ព',
    'rejected': 'បានបដិសេធ',
    'overview': 'ទិដ្ឋភាពទូទៅ',
    'content': 'មាតិកា',
    'my news': 'ព័ត៌មានរបស់ខ្ញុំ',
    'media': 'មេឌៀ',
    'ai tools': 'ឧបករណ៍ AI',
    'ai assistant': 'ជំនួយការ AI',
    'design': 'រចនា',
    'homepage builder': 'អ្នកបង្កើតទំព័រដើម',
    'ads control': 'គ្រប់គ្រងពាណិជ្ជកម្ម',
    'site settings': 'ការកំណត់គេហទំព័រ',
    'administration': 'ការគ្រប់គ្រង',
    'users': 'អ្នកប្រើប្រាស់',
    'messages': 'សារ',
    'newsletter': 'សារព័ត៌មានជាវ',
    'analytics': 'វិភាគ',
    'structure': 'រចនាសម្ព័ន្ធ',
    'organize your newsroom topics': 'រៀបចំប្រធានបទបន្ទប់ព័ត៌មានរបស់អ្នក',
    'total': 'សរុប',
    'new category': 'ប្រភេទថ្មី',
    'active': 'សកម្ម',
    'hidden': 'លាក់',
    'no categories yet': 'មិនទាន់មានប្រភេទ',
    'create your first category to organize news': 'បង្កើតប្រភេទដំបូងរបស់អ្នកដើម្បីរៀបចំព័ត៌មាន',
    'create category': 'បង្កើតប្រភេទ',
    'edit category': 'កែសម្រួលប្រភេទ',
    'delete category': 'លុបប្រភេទ',
    'category name': 'ឈ្មោះប្រភេទ',
    'description (optional)': 'ការពិពណ៌នា (ជម្រើស)',
    'category image url (optional)': 'URL រូបភាពប្រភេទ (ជម្រើស)',
    'color': 'ពណ៌',
    'brief description of this category...': 'ពិពណ៌នាសង្ខេបអំពីប្រភេទនេះ...',
    'e.g., technology, sports, politics': 'ឧ. បច្ចេកវិទ្យា កីឡា នយោបាយ',
    'https://... or /uploads/...': 'https://... ឬ /uploads/...',
    'create': 'បង្កើត',
    'update': 'ធ្វើបច្ចុប្បន្នភាព',
    'edit': 'កែសម្រួល',
    'update category': 'ធ្វើបច្ចុប្បន្នភាពប្រភេទ',
    'category name is required': 'ត្រូវការឈ្មោះប្រភេទ',
    'category updated successfully': 'បានអាប់ដេតប្រភេទដោយជោគជ័យ',
    'category created successfully': 'បានបង្កើតប្រភេទដោយជោគជ័យ',
    'category deleted successfully': 'បានលុបប្រភេទដោយជោគជ័យ',
    'are you sure you want to delete': 'តើអ្នកប្រាកដថាចង់លុប',
    'this action cannot be undone.': 'សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយបានទេ។',
    'business': 'អាជីវកម្ម',
    'entertainment': 'កម្សាន្ត',
    'lifestyle': 'របៀបរស់នៅ',
    'sports': 'កីឡា',
    'technology': 'បច្ចេកវិទ្យា',
    'business news imported from trusted rss feeds': 'ព័ត៌មានអាជីវកម្មនាំចូលពីប្រភព RSS ដែលអាចទុកចិត្តបាន',
    'entertainment news imported from trusted rss feeds': 'ព័ត៌មានកម្សាន្តនាំចូលពីប្រភព RSS ដែលអាចទុកចិត្តបាន',
    'lifestyle news imported from trusted rss feeds': 'ព័ត៌មានរបៀបរស់នៅនាំចូលពីប្រភព RSS ដែលអាចទុកចិត្តបាន',
    'news news imported from trusted rss feeds': 'ព័ត៌មាននាំចូលពីប្រភព RSS ដែលអាចទុកចិត្តបាន',
    'sports news imported from trusted rss feeds': 'ព័ត៌មានកីឡានាំចូលពីប្រភព RSS ដែលអាចទុកចិត្តបាន',
    'technology news imported from trusted rss feeds': 'ព័ត៌មានបច្ចេកវិទ្យានាំចូលពីប្រភព RSS ដែលអាចទុកចិត្តបាន',
    'status': 'ស្ថានភាព',
    'review and manage every news item across the newsroom.': 'ពិនិត្យ និងគ្រប់គ្រងព័ត៌មានទាំងអស់នៅទូទាំងបន្ទប់ព័ត៌មាន។',
    'drafts, submissions, and published stories in one place.': 'សេចក្តីព្រាង ការដាក់ស្នើ និងព័ត៌មានដែលបានបោះពុម្ព នៅកន្លែងតែមួយ។',
    'search by title...': 'ស្វែងរកតាមចំណងជើង...',
    'translation saved': 'បានរក្សាទុកការបកប្រែ',
    'translation published': 'បានបោះពុម្ពការបកប្រែ',
    'failed to save translation': 'រក្សាទុកការបកប្រែបរាជ័យ',
    'failed to publish translation': 'បោះពុម្ពការបកប្រែបរាជ័យ',
    'source news content is required before translation': 'ត្រូវការមាតិកាព័ត៌មានដើមមុនពេលបកប្រែ',
    'auto-translated to': 'បានបកប្រែស្វ័យប្រវត្តិទៅ',
    'auto translation failed': 'ការបកប្រែស្វ័យប្រវត្តិបរាជ័យ',
    'image size must be less than 5mb': 'ទំហំរូបភាពត្រូវតែតិចជាង 5MB',
    'image uploaded successfully': 'បានផ្ទុករូបភាពឡើងដោយជោគជ័យ',
    'failed to upload image': 'ផ្ទុករូបភាពឡើងបរាជ័យ',
    'maximum 10 tags allowed': 'អាចដាក់បានអតិបរមា 10 ស្លាក',
    'title is required': 'ត្រូវការចំណងជើង',
    'title must be less than 200 characters': 'ចំណងជើងត្រូវតែតិចជាង 200 តួអក្សរ',
    'please select a category': 'សូមជ្រើសរើសប្រភេទ',
    'excerpt must be less than 500 characters': 'សេចក្តីសង្ខេបត្រូវតែតិចជាង 500 តួអក្សរ',
    'news content is required': 'ត្រូវការមាតិកាព័ត៌មាន',
    'draft saved successfully': 'បានរក្សាទុកសេចក្តីព្រាងដោយជោគជ័យ',
    'news submitted for review': 'បានដាក់ស្នើព័ត៌មានសម្រាប់ពិនិត្យ',
    'failed to save news': 'រក្សាទុកព័ត៌មានបរាជ័យ',
    'failed to generate preview': 'បង្កើតការមើលជាមុនបរាជ័យ',
    'select translation language': 'ជ្រើសរើសភាសាបកប្រែ',
    'translation title is required': 'ត្រូវការចំណងជើងបកប្រែ',
    'news content is required for translation': 'ត្រូវការមាតិកាព័ត៌មានសម្រាប់ការបកប្រែ',
    'failed to prepare translation content': 'រៀបចំមាតិកាបកប្រែបរាជ័យ',
    'edit news': 'កែសម្រួលព័ត៌មាន',
    'back': 'ថយក្រោយ',
    'create and publish amazing content': 'បង្កើត និងបោះពុម្ពមាតិកាដ៏ល្អឥតខ្ចោះ',
    'save draft': 'រក្សាទុកសេចក្តីព្រាង',
    'submit for review': 'ដាក់ស្នើសម្រាប់ពិនិត្យ',
    'news title *': 'ចំណងជើងព័ត៌មាន *',
    'enter a compelling title...': 'បញ្ចូលចំណងជើងទាក់ទាញ...',
    'characters': 'តួអក្សរ',
    'featured image': 'រូបភាពលេចធ្លោ',
    'uploading image...': 'កំពុងផ្ទុករូបភាព...',
    'please wait while your image is being uploaded': 'សូមរង់ចាំ ខណៈពេលរូបភាពរបស់អ្នកកំពុងត្រូវបានផ្ទុកឡើង',
    'upload a featured image for your news': 'ផ្ទុករូបភាពលេចធ្លោសម្រាប់ព័ត៌មានរបស់អ្នក',
    'jpg, png or webp. max 5mb.': 'JPG, PNG ឬ WEBP។ អតិបរមា 5MB។',
    'choose image': 'ជ្រើសរើសរូបភាព',
    'news content *': 'មាតិកាព័ត៌មាន *',
    'use rich text formatting': 'ប្រើទម្រង់អត្ថបទបែបសម្បូរបែប',
    'failed to load news content. please refresh or try again.': 'ផ្ទុកមាតិកាព័ត៌មានបរាជ័យ។ សូមផ្ទុកឡើងវិញ ឬព្យាយាមម្តងទៀត។',
    'start writing your news...': 'ចាប់ផ្តើមសរសេរព័ត៌មានរបស់អ្នក...',
    'tip: use "/" to see formatting options. drag blocks to reorder them.': 'គន្លឹះ៖ ប្រើ "/" ដើម្បីមើលជម្រើសទម្រង់។ អូសប្លុកដើម្បីរៀបលំដាប់ឡើងវិញ។',
    'translation content': 'មាតិកាបកប្រែ',
    'no translation yet': 'មិនទាន់មានការបកប្រែ',
    'target language': 'ភាសាគោលដៅ',
    'translated title': 'ចំណងជើងដែលបានបកប្រែ',
    'translated excerpt': 'សេចក្តីសង្ខេបដែលបានបកប្រែ',
    'auto translate': 'បកប្រែស្វ័យប្រវត្តិ',
    'save translation': 'រក្សាទុកការបកប្រែ',
    'write translated content in': 'សរសេរមាតិកាដែលបានបកប្រែជា',
    'excerpt': 'សេចក្តីសង្ខេប',
    'brief description of your news (shown in previews)': 'សេចក្តីពិពណ៌នាសង្ខេបអំពីព័ត៌មានរបស់អ្នក (បង្ហាញនៅពេលមើលជាមុន)',
    'category *': 'ប្រភេទ *',
    'no categories available. ask an admin to create some.': 'មិនមានប្រភេទអាចប្រើបានទេ។ សូមស្នើអ្នកគ្រប់គ្រងឱ្យបង្កើត។',
    'tags': 'ស្លាក',
    'add a tag...': 'បន្ថែមស្លាក...',
    'add': 'បន្ថែម',
    'press enter or click add to add tags': 'ចុច Enter ឬចុច បន្ថែម ដើម្បីបន្ថែមស្លាក',
    'news options': 'ជម្រើសព័ត៌មាន',
    'publishing info': 'ព័ត៌មានបោះពុម្ពផ្សាយ',
    'created': 'បានបង្កើត',
    'review': 'ពិនិត្យ',
    'in_progress': 'កំពុងដំណើរការ',
    'all posts': 'ប្រកាសទាំងអស់',
    'my posts': 'ប្រកាសរបស់ខ្ញុំ',
    'total posts': 'ប្រកាសសរុប',
    'new post': 'ប្រកាសថ្មី',
    'post insights': 'ការវិភាគប្រកាស',
    'recent posts': 'ប្រកាសថ្មីៗ',
    'no recent posts': 'មិនមានប្រកាសថ្មីៗ',
    'no top posts yet': 'មិនទាន់មានប្រកាសពេញនិយម',
    'write new post': 'សរសេរប្រកាសថ្មី',
    'view my posts': 'មើលប្រកាសរបស់ខ្ញុំ',
    'review pending posts': 'ពិនិត្យប្រកាសកំពុងរង់ចាំ',
    'review and manage every post across the newsroom.': 'ពិនិត្យ និងគ្រប់គ្រងប្រកាសទាំងអស់នៅទូទាំងបន្ទប់ព័ត៌មាន។',
    'view post': 'មើលប្រកាស',
    'posts': 'ប្រកាស',
    'no posts found': 'រកមិនឃើញប្រកាស',
    'no posts yet': 'មិនទាន់មានប្រកាស',
    'try adjusting your filters or create the first post.': 'សាកល្បងកែតម្រូវតម្រង ឬបង្កើតប្រកាសដំបូង។',
    'start writing your first post.': 'ចាប់ផ្តើមសរសេរប្រកាសដំបូងរបស់អ្នក។',
    'delete post': 'លុបប្រកាស',
    'are you sure you want to delete this post? this action cannot be undone.': 'តើអ្នកប្រាកដថាចង់លុបប្រកាសនេះទេ? សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយបានទេ។',
    'pending posts': 'ប្រកាសកំពុងរង់ចាំ',
    'posts awaiting your approval': 'ប្រកាសកំពុងរង់ចាំការអនុម័តរបស់អ្នក',
    'no posts pending review': 'មិនមានប្រកាសរង់ចាំពិនិត្យ',
    'approve post': 'អនុម័តប្រកាស',
    'are you sure you want to approve this post for publication?': 'តើអ្នកប្រាកដថាចង់អនុម័តប្រកាសនេះសម្រាប់បោះពុម្ពផ្សាយទេ?',
    'reject post': 'បដិសេធប្រកាស',
    'post type': 'ប្រភេទប្រកាស',
    'post type *': 'ប្រភេទប្រកាស *',
    'post title': 'ចំណងជើងប្រកាស',
    'post title *': 'ចំណងជើងប្រកាស *',
    'post content': 'មាតិកាប្រកាស',
    'post content *': 'មាតិកាប្រកាស *',
    'post content (optional for video)': 'មាតិកាប្រកាស (ជម្រើសសម្រាប់វីដេអូ)',
    'post options': 'ជម្រើសប្រកាស',
    'featured post': 'ប្រកាសលេចធ្លោ',
    'breaking post': 'ប្រកាសបន្ទាន់',
    'mark as breaking content': 'សម្គាល់ជា​មាតិកាបន្ទាន់',
    'brief description of your post (shown in previews)': 'សេចក្តីពិពណ៌នាសង្ខេបអំពីប្រកាសរបស់អ្នក (បង្ហាញនៅពេលមើលជាមុន)',
    'start writing your post...': 'ចាប់ផ្តើមសរសេរប្រកាសរបស់អ្នក...',
    'failed to load post content. please refresh or try again.': 'ផ្ទុកមាតិកាប្រកាសបរាជ័យ។ សូមផ្ទុកឡើងវិញ ឬព្យាយាមម្តងទៀត។',
    'post submitted for review': 'បានដាក់ស្នើប្រកាសសម្រាប់ពិនិត្យ',
    'failed to save post': 'រក្សាទុកប្រកាសបរាជ័យ',
    'source post content is required before translation': 'ត្រូវការមាតិកាប្រកាសដើមមុនពេលបកប្រែ',
    'post content is required': 'ត្រូវការមាតិកាប្រកាស',
    'post content is required for translation': 'ត្រូវការមាតិកាប្រកាសសម្រាប់ការបកប្រែ',
    'publish': 'បោះពុម្ពផ្សាយ',
    'facebook url': 'តំណ Facebook',
    'facebook url *': 'តំណ Facebook *',
    'facebook post': 'ប្រកាស Facebook',
    'facebook video': 'វីដេអូ Facebook',
    'facebook reel': 'Facebook Reel',
    'facebook posts, videos, and reels in one place': 'ប្រកាស វីដេអូ និង Reel របស់ Facebook នៅកន្លែងតែមួយ',
    'video preview': 'មើលវីដេអូជាមុន',
    'open on facebook': 'បើកនៅលើ Facebook',
    'view on facebook': 'មើលលើ Facebook',
    'paste a public facebook video, reel, or post link': 'បិទភ្ជាប់តំណ Facebook សាធារណៈ (វីដេអូ Reel ឬប្រកាស)',
    'use a valid facebook link (post/video/reel)': 'សូមប្រើតំណ Facebook ត្រឹមត្រូវ (ប្រកាស/វីដេអូ/Reel)',
    'this video cannot be embedded right now.': 'វីដេអូនេះមិនអាចបង្កប់បាននៅពេលនេះទេ។',
    'valid facebook video url is required for video posts': 'ត្រូវការតំណវីដេអូ Facebook ត្រឹមត្រូវសម្រាប់ប្រកាសវីដេអូ',
    'optional caption or context for this video post': 'ចំណងជើងរង ឬបរិបទ (ជម្រើស) សម្រាប់ប្រកាសវីដេអូនេះ',
    'optional caption, context, or transcript...': 'ចំណងជើងរង បរិបទ ឬអត្ថបទបកស្រាយ (ជម្រើស)...',
    'if left empty, excerpt/title will be used as fallback content automatically.': 'បើទុកទទេ ប្រព័ន្ធនឹងប្រើសេចក្តីសង្ខេប/ចំណងជើងជាមាតិកាជំនួសដោយស្វ័យប្រវត្តិ។',
    'required fields': 'វាលដែលត្រូវបំពេញ',
    'completed': 'បានបំពេញ',
    'select type first. required fields update automatically.': 'សូមជ្រើសប្រភេទជាមុនសិន។ វាលត្រូវបំពេញនឹងអាប់ដេតដោយស្វ័យប្រវត្តិ។',
    'all types': 'ប្រភេទទាំងអស់',
    'video posts': 'ប្រកាសវីដេអូ',
    'video': 'វីដេអូ',
    'videos': 'វីដេអូ',
    'latest videos': 'វីដេអូចុងក្រោយ',
    'manage facebook post, video, and reel links in one place. homepage video sections read from this list.': 'គ្រប់គ្រងតំណ Facebook (ប្រកាស វីដេអូ និង Reel) នៅកន្លែងតែមួយ។ ផ្នែកវីដេអូលើទំព័រដើមនឹងអានពីបញ្ជីនេះ។',
    'no facebook videos configured yet. add links in the video posts dashboard page.': 'មិនទាន់មានវីដេអូ Facebook បានកំណត់ទេ។ បន្ថែមតំណនៅទំព័រគ្រប់គ្រងប្រកាសវីដេអូ។',
    'unsaved changes': 'មានការផ្លាស់ប្តូរមិនទាន់រក្សាទុក',
    'add video': 'បន្ថែមវីដេអូ',
    'enabled': 'បើកប្រើ',
    'valid links': 'តំណត្រឹមត្រូវ',
    'duplicates': 'ស្ទួន',
    'video list': 'បញ្ជីវីដេអូ',
    'paste facebook links only. reorder items to control appearance.': 'បិទភ្ជាប់តែតំណ Facebook ប៉ុណ្ណោះ។ រៀបលំដាប់ធាតុដើម្បីគ្រប់គ្រងការបង្ហាញ។',
    'no video posts yet': 'មិនទាន់មានប្រកាសវីដេអូ',
    'add first video post': 'បន្ថែមប្រកាសវីដេអូដំបូង',
    'duplicate': 'ស្ទួន',
    'ready': 'រួចរាល់',
    'invalid': 'មិនត្រឹមត្រូវ',
    'move up': 'ផ្លាស់ទីឡើងលើ',
    'move down': 'ផ្លាស់ទីចុះក្រោម',
    'headline': 'ចំណងជើង',
    'video headline': 'ចំណងជើងវីដេអូ',
    'published date (optional)': 'ថ្ងៃបោះពុម្ព (ជម្រើស)',
    'display style': 'រចនាប័ទ្មបង្ហាញ',
    'auto (detect from facebook link)': 'ស្វ័យប្រវត្តិ (រកឃើញពីតំណ Facebook)',
    'landscape (16:9)': 'ផ្ដេក (16:9)',
    'reel (9:16)': 'Reel (9:16)',
    'facebook link (post/video/reel)': 'តំណ Facebook (ប្រកាស/វីដេអូ/Reel)',
    'invalid facebook url': 'តំណ Facebook មិនត្រឹមត្រូវ',
    'duplicate facebook url': 'តំណ Facebook ស្ទួន',
    'short description': 'សេចក្តីពិពណ៌នាខ្លី',
    'select a category': 'ជ្រើសរើសប្រភេទ',
    'please upload an image file': 'សូមផ្ទុកឯកសាររូបភាព',
    'upload a featured image for your post': 'ផ្ទុករូបភាពលេចធ្លោសម្រាប់ប្រកាសរបស់អ្នក',
    'show in featured section': 'បង្ហាញនៅផ្នែកលេចធ្លោ',
    'mark as machine translated': 'សម្គាល់ថាបកប្រែដោយម៉ាស៊ីន',
    'remove video post': 'ដកប្រកាសវីដេអូ',
    'are you sure you want to remove this video post?': 'តើអ្នកប្រាកដថាចង់ដកប្រកាសវីដេអូនេះទេ?',
    'remove': 'ដកចេញ',
    'invalid facebook links at row(s)': 'តំណ Facebook មិនត្រឹមត្រូវនៅជួរទី',
    'duplicate facebook links at row(s)': 'តំណ Facebook ស្ទួននៅជួរទី',
    'save': 'រក្សាទុក',
  },
  zh: {
    'featured': '精选',
    'highlight': '亮点',
    'more featured': '更多精选',
    'breaking': '突发',
    'alert': '提醒',
    'latest': '最新',
    'trending': '热门',
    'news': '新闻',
    'categories': '分类',
    'stories': '故事',
    'magazine': '杂志',
    'editors': '编辑',
    'spotlight': '焦点',
    'quick update': '快讯',
    'stay updated': '保持更新',
    'fresh headlines drop every hour. stay ahead with real-time coverage.': '每小时更新最新头条，实时掌握动态。',
    'no news available': '暂无新闻',
    'no featured news. mark news as featured in the dashboard.': '暂无精选新闻，请在后台标记精选。',
    'no additional featured news available.': '暂无更多精选新闻。',
    'no breaking news in the dashboard.': '后台暂无突发新闻。',
    'no breaking news yet': '暂无突发新闻',
    'no news published yet': '暂无已发布新闻',
    'no trending news': '暂无热门新闻',
    'no editor picks available': '暂无编辑推荐',
    'no news in this category yet': '该分类暂无新闻',
    'category': '分类',
    'power, policy, and people shaping the week.': '本周影响局势的力量、政策与人物。',
    'more': '更多',
    'view all': '查看全部',
    'see more': '查看更多',
    'all news': '全部新闻',
    'browse news': '浏览新闻',
    'search results': '搜索结果',
    'search posts, topics, authors...': '搜索帖子、主题、作者...',
    'news feed': '新闻流',
    'find stories faster with search and category filters.': '通过搜索和分类筛选，更快找到内容。',
    'loading more...': '正在加载更多...',
    'load more': '加载更多',
    'no news found': '未找到新闻',
    'clear search': '清除搜索',
    'browse by topic': '按主题浏览',
    'topics': '主题',
    'popular': '热门',
    'clear': '清除',
    'no categories found': '未找到分类',
    'try a different search, or browse all news.': '试试其他关键词，或浏览全部新闻。',
    'topic page': '主题页',
    'explore': '探索',
    'back to news': '返回新闻',
    'share:': '分享：',
    'copied': '已复制',
    'more news': '更多新闻',
    'related news': '相关新闻',
    'no related news found': '未找到相关新闻',
    'no additional news available': '暂无更多新闻',
    'comments': '评论',
    'reply': '回复',
    'cancel': '取消',
    'write a reply...': '写下回复...',
    'your name': '你的姓名',
    'your email': '你的邮箱',
    'share your thoughts...': '分享你的想法...',
    'write a comment...': '写评论...',
    'your name *': '你的姓名 *',
    'your email *': '你的邮箱 *',
    'comments are moderated before appearing': '评论需审核后显示',
    'posting...': '发布中...',
    'post comment': '发布评论',
    'no comments yet. be the first to share your thoughts!': '还没有评论，来发表第一条吧！',
    'load more comments': '加载更多评论',
    'delete comment': '删除评论',
    'are you sure you want to delete this comment?': '确定要删除这条评论吗？',
    'delete': '删除',
    'news not found': '未找到新闻',
    "the news you're looking for doesn't exist.": '你查找的新闻不存在。',
    'sign in': '登录',
    'continue with google': '使用 Google 继续',
    'continue with facebook': '使用 Facebook 继续',
    'or use email': '或使用邮箱',
    'email': '邮箱',
    'password': '密码',
    'remember me': '记住我',
    'forgot password?': '忘记密码？',
    "don't have an account?": '还没有账号？',
    'sign up': '注册',
    'demo accounts:': '演示账号：',
    'create account': '创建账号',
    'first name': '名字',
    'last name': '姓氏',
    'gender': '性别',
    'birthday': '生日',
    'day': '日',
    'month': '月',
    'year': '年',
    'confirm password': '确认密码',
    'already have an account?': '已有账号？',
    'checking email availability...': '正在检查邮箱可用性...',
    'email is available': '邮箱可用',
    'could not verify email right now': '暂时无法验证邮箱',
    'password strength:': '密码强度：',
    'weak': '弱',
    'fair': '一般',
    'good': '良好',
    'strong': '强',
    'very strong': '非常强',
    'complete your profile': '完善资料',
    'we need your gender and birthday to finish your account setup.': '我们需要你的性别和生日来完成账号设置。',
    'select gender': '选择性别',
    'save & continue': '保存并继续',
    'account': '账号',
    'edit profile': '编辑资料',
    'bio': '简介',
    'tell us about yourself...': '介绍一下你自己...',
    'save changes': '保存更改',
    'tap the camera icon to choose, crop, and update your photo.': '点击相机图标选择、裁剪并更新头像。',
    'edit profile picture': '编辑头像',
    'drag image to reposition inside the circle': '拖动图片调整圆形区域内位置',
    'zoom': '缩放',
    'rotation': '旋转',
    'reset': '重置',
    'done & update': '完成并更新',
    'processing...': '处理中...',
    'confirm action': '确认操作',
    'are you sure you want to proceed?': '确定要继续吗？',
    'confirm': '确认',
    'alert': '提示',
    'ok': '确定',
    'advertisement': '广告',
    'ad': '广告',
    'back to website': '返回网站',
    'page not found': '页面未找到',
    'go home': '返回首页',
    'section': '版块',
    'breaking news': '突发新闻',
    'latest news': '最新新闻',
    'latest alerts and urgent updates': '最新提醒与紧急更新',
    'view all news': '查看全部新闻',
    'uncategorized': '未分类',
    'admin': '管理员',
    'anonymous': '匿名',
    'edited': '已编辑',
    'approved': '已通过',
    'views': '次浏览',
    'close ad': '关闭广告',
    'find stories faster with topic pages—search, sort, and jump into what you care about.': '通过主题页更快找到内容，支持搜索、排序并直达你关心的话题。',
    'explore the latest updates in': '探索以下最新动态',
    'view': '查看',
    'more stories': '更多故事',
    'latest news & updates': '最新新闻与更新',
    'required': '必填',
    'email is required': '邮箱为必填项',
    'password is required': '密码为必填项',
    'invalid email address': '邮箱地址无效',
    'invalid gender': '性别无效',
    'birthday is required': '生日为必填项',
    'birthday is invalid': '生日无效',
    'birthday cannot be in the future': '生日不能晚于今天',
    'min 8 characters': '至少 8 个字符',
    'must include letters and numbers': '必须包含字母和数字',
    'passwords do not match': '两次密码不一致',
    'email already registered': '该邮箱已注册',
    'please select your gender': '请选择你的性别',
    'please select your birthday': '请选择你的生日',
    'please complete the required profile fields.': '请完善必填资料。',
    'please select an image file': '请选择图片文件',
    'image must be less than 5mb': '图片大小必须小于 5MB',
    'could not read this image': '无法读取该图片',
    'profile picture updated!': '头像已更新！',
    'upload failed': '上传失败',
    'about us': '关于我们',
    'an unexpected error occurred. please try again or go back to the home page.': '发生了意外错误。请重试或返回首页。',
    'back to login': '返回登录',
    'back to pending': '返回待处理',
    'balanced coverage that avoids sensational framing.': '平衡报道，避免夸张渲染。',
    'browse categories': '浏览分类',
    'building trust through clear, independent journalism.': '通过清晰、独立的新闻报道建立信任。',
    'close preview': '关闭预览',
    'complete profile': '完善资料',
    'confirm subscription': '确认订阅',
    'confirmation failed': '确认失败',
    'confirming subscription': '正在确认订阅',
    'connect with': '联系',
    'contact': '联系',
    'contact team': '联系团队',
    'contact us': '联系我们',
    'continuous updates when facts evolve.': '当事实变化时持续更新。',
    'coverage': '报道范围',
    'draft': '草稿',
    'editor': '编辑',
    'email address': '邮箱地址',
    'email verified!': '邮箱验证成功！',
    'enable browser notifications': '启用浏览器通知',
    'enter your new password below.': '请在下方输入新密码。',
    'explore news': '探索新闻',
    'fact-checked stories with clear sources and context.': '经过事实核查，来源与背景清晰。',
    'failed to load': '加载失败',
    'female': '女',
    'follow our reporting and be part of the conversation.': '关注我们的报道，参与公共讨论。',
    'forgot password': '忘记密码',
    'from our newsroom': '来自我们的新闻编辑部',
    'go to login': '前往登录',
    'independent': '独立',
    'inform clearly. explain deeply. serve the public.': '清晰传达，深入解释，服务公众。',
    'invalid link': '无效链接',
    'join our community': '加入我们的社区',
    'male': '男',
    'mark all read': '全部标记为已读',
    'min': '分钟',
    'new': '新',
    'new password': '新密码',
    'newsroom workflow': '新闻编辑流程',
    'no notifications yet': '暂无通知',
    'no recent stories available right now.': '当前暂无最新报道。',
    'notifications': '通知',
    'oops! something went wrong': '哎呀，出错了',
    'our mission': '我们的使命',
    'password reset!': '密码已重置！',
    'phnom penh, cambodia': '柬埔寨金边',
    'please wait while we confirm your subscription...': '请稍候，我们正在确认你的订阅...',
    'please wait while we update your subscription...': '请稍候，我们正在更新你的订阅...',
    'please wait while we verify your email address...': '请稍候，我们正在验证你的邮箱地址...',
    'preview': '预览',
    'preview error': '预览错误',
    'preview mode': '预览模式',
    'preview mode - this is how your news will look when published': '预览模式 - 这是新闻发布后的显示效果',
    'processing': '处理中',
    'redirecting to login...': '正在跳转到登录页...',
    'remember your password?': '想起密码了？',
    'request new link': '请求新链接',
    'reset password': '重置密码',
    'resetting...': '重置中...',
    'send message': '发送消息',
    'send reset link': '发送重置链接',
    'send us a message': '给我们留言',
    'sending...': '发送中...',
    'sign-in failed': '登录失败',
    'signing you in': '正在为你登录',
    'something went wrong': '出现问题',
    'stay updated with our latest investigations, explainers, and local stories that shape public dialogue.': '关注我们最新的调查、解读和影响公共讨论的本地报道。',
    'step': '步骤',
    'subscribed!': '订阅成功！',
    'this news is not available for preview.': '这条新闻暂不可预览。',
    'to make journalism more useful for everyday readers. our newsroom focuses on verified reporting, practical context, and responsible storytelling that values people over noise.': '让新闻对日常读者更有价值。我们的编辑部专注于可验证报道、实用背景和负责任的叙事。',
    'try again': '重试',
    'unsubscribe': '取消订阅',
    'unsubscribe failed': '取消订阅失败',
    'unsubscribed': '已取消订阅',
    'untitled': '无标题',
    'untitled news': '无标题新闻',
    'updates': '更新',
    'verification failed': '验证失败',
    'verify email': '验证邮箱',
    'verifying email': '正在验证邮箱',
    'view all notifications': '查看全部通知',
    'we created': '我们创建了',
    'what we cover': '我们的报道内容',
    'writer': '作者',
    'english': '英语',
    'khmer': '高棉语',
    'chinese': '中文',
    'your trusted source for quality news, insightful stories, and in-depth coverage of the issues that matter.': '你可信赖的高质量新闻来源，提供深度故事与重要议题的深入报道。',
    'your trusted source for quality news, insightful articles, and in-depth coverage of the stories that matter.': '你可信赖的高质量新闻来源，提供深度文章与重要报道。',
    'select language': '选择语言',
    'avatar': '头像',
    "have a question? we'd love to hear from you.": '有问题吗？我们很乐意听你反馈。',
    "enter your email and we'll send you a reset link.": '输入你的邮箱，我们会发送重置链接。',
    'open': '打开',
    'pending': '待处理',
    'no news in this category': '该分类暂无新闻',
    'this article is not available in the selected language yet. showing english version.': '该文章暂未提供所选语言，当前显示英文版本。',
    "we're sorry, but something unexpected happened. our team has been notified.": '很抱歉，发生了意外情况。我们的团队已收到通知。',
    '© {year} {sitename}. all rights reserved.': '© {year} {siteName}。保留所有权利。',
    'all rights reserved.': '保留所有权利。',
    'social sign-in failed. please try again.': '社交登录失败，请重试。',
    'missing social login session. please try again.': '缺少社交登录会话，请重试。',
    'could not complete social sign-in. please try again.': '无法完成社交登录，请重试。',
    'invalid verification link. please request a new verification email.': '验证链接无效，请重新申请验证邮件。',
    'your email has been verified successfully!': '你的邮箱已验证成功！',
    'verification failed. the link may have expired.': '验证失败，链接可能已过期。',
    'an error occurred. please try again later.': '发生错误，请稍后重试。',
    'invalid confirmation link. please subscribe again.': '确认链接无效，请重新订阅。',
    'your subscription has been confirmed!': '你的订阅已确认！',
    'confirmation failed. the link may have expired.': '确认失败，链接可能已过期。',
    'invalid unsubscribe link.': '取消订阅链接无效。',
    'you have been unsubscribed successfully.': '你已成功取消订阅。',
    'unsubscribe failed. please try again later.': '取消订阅失败，请稍后重试。',
    'if an account exists with this email, you will receive a password reset link.': '如果该邮箱对应账号存在，你将收到密码重置链接。',
    'something went wrong. please try again.': '出了点问题，请重试。',
    'invalid reset link. please request a new password reset.': '重置链接无效，请重新申请重置密码。',
    'passwords do not match.': '两次密码不一致。',
    'password must be at least 8 characters.': '密码至少需要 8 个字符。',
    'your password has been reset successfully!': '你的密码已成功重置！',
    'reset failed. the link may have expired.': '重置失败，链接可能已过期。',
    'dashboard': '仪表盘',
    'activity': '活动',
    'welcome back,': '欢迎回来，',
    'track newsroom momentum and stay ahead.': '跟踪编辑部节奏，始终保持领先。',
    'last 7 days': '最近 7 天',
    'last 30 days of traffic': '最近 30 天流量',
    'items': '条目',
    'total views': '总浏览量',
    'views over time': '浏览趋势',
    'published per day': '每日发布量',
    'editorial output pace': '编辑产出节奏',
    'status mix': '状态构成',
    'published vs pending vs draft': '已发布 vs 待审核 vs 草稿',
    'category performance': '分类表现',
    'views by category': '按分类浏览量',
    'no category data yet': '暂无分类数据',
    'ad reach & ctr': '广告触达与点击率',
    'impressions vs clicks (last 30 days)': '展示 vs 点击（最近 30 天）',
    'total ctr': '总 CTR',
    'impressions': '展示量',
    'clicks': '点击量',
    'content momentum': '内容动能',
    'top stories': '热门新闻',
    'no top news yet': '暂无热门新闻',
    'recent news': '最新新闻',
    'no recent news': '暂无最新新闻',
    'quick actions': '快捷操作',
    'write new news': '撰写新新闻',
    'view my news': '查看我的新闻',
    'review pending news': '审核待处理新闻',
    'ad insights': '广告洞察',
    'news insights': '新闻洞察',
    'all statuses': '全部状态',
    'title': '标题',
    'author': '作者',
    'date': '日期',
    'view news': '查看新闻',
    'insights': '洞察',
    'unknown': '未知',
    'page': '第',
    'of': '/',
    'previous': '上一页',
    'next': '下一页',
    'no news yet': '暂无新闻',
    'try adjusting your filters or create the first news item.': '请调整筛选条件，或创建第一条新闻。',
    'start writing your first news item.': '开始撰写你的第一条新闻。',
    'delete news': '删除新闻',
    'are you sure you want to delete this news? this action cannot be undone.': '确定要删除这条新闻吗？此操作不可撤销。',
    'pending news': '待审核新闻',
    'pending review': '待审核',
    'news awaiting your approval': '等待你审核的新闻',
    'by': '作者',
    'approve': '批准',
    'reject': '拒绝',
    'all caught up!': '全部处理完毕！',
    'no news pending review': '暂无待审核新闻',
    'approve news': '批准新闻',
    'are you sure you want to approve this news for publication?': '确定要批准这条新闻发布吗？',
    'reject news': '拒绝新闻',
    'rejection reason': '拒绝原因',
    'enter reason for rejection...': '输入拒绝原因...',
    'please provide a reason for rejection': '请提供拒绝原因',
    'validation error': '验证错误',
    'profile': '个人资料',
    'no data': '暂无数据',
    'no data available': '暂无可用数据',
    'archived': '已归档',
    'new news': '新新闻',
    'published': '已发布',
    'rejected': '已拒绝',
    'overview': '概览',
    'content': '内容',
    'my news': '我的新闻',
    'media': '媒体',
    'ai tools': 'AI 工具',
    'ai assistant': 'AI 助手',
    'design': '设计',
    'homepage builder': '首页构建器',
    'ads control': '广告管理',
    'site settings': '站点设置',
    'administration': '管理',
    'users': '用户',
    'messages': '消息',
    'newsletter': '新闻订阅',
    'analytics': '分析',
    'structure': '结构',
    'organize your newsroom topics': '整理你的新闻编辑部主题',
    'total': '总计',
    'new category': '新分类',
    'active': '启用',
    'hidden': '隐藏',
    'no categories yet': '暂无分类',
    'create your first category to organize news': '创建你的第一个分类来整理新闻',
    'create category': '创建分类',
    'edit category': '编辑分类',
    'delete category': '删除分类',
    'category name': '分类名称',
    'description (optional)': '描述（可选）',
    'category image url (optional)': '分类图片 URL（可选）',
    'color': '颜色',
    'brief description of this category...': '简要描述这个分类...',
    'e.g., technology, sports, politics': '例如：科技、体育、政治',
    'https://... or /uploads/...': 'https://... 或 /uploads/...',
    'create': '创建',
    'update': '更新',
    'edit': '编辑',
    'update category': '更新分类',
    'category name is required': '分类名称为必填项',
    'category updated successfully': '分类更新成功',
    'category created successfully': '分类创建成功',
    'category deleted successfully': '分类删除成功',
    'are you sure you want to delete': '你确定要删除',
    'this action cannot be undone.': '此操作无法撤销。',
    'business': '商业',
    'entertainment': '娱乐',
    'lifestyle': '生活方式',
    'sports': '体育',
    'technology': '科技',
    'business news imported from trusted rss feeds': '来自可信 RSS 源的商业新闻',
    'entertainment news imported from trusted rss feeds': '来自可信 RSS 源的娱乐新闻',
    'lifestyle news imported from trusted rss feeds': '来自可信 RSS 源的生活方式新闻',
    'news news imported from trusted rss feeds': '来自可信 RSS 源的新闻',
    'sports news imported from trusted rss feeds': '来自可信 RSS 源的体育新闻',
    'technology news imported from trusted rss feeds': '来自可信 RSS 源的科技新闻',
    'status': '状态',
    'review and manage every news item across the newsroom.': '审核并管理新闻编辑部中的所有新闻。',
    'drafts, submissions, and published stories in one place.': '草稿、提交和已发布新闻都集中在这里。',
    'search by title...': '按标题搜索...',
    'translation saved': '翻译已保存',
    'translation published': '翻译已发布',
    'failed to save translation': '保存翻译失败',
    'failed to publish translation': '发布翻译失败',
    'source news content is required before translation': '翻译前需要原始新闻内容',
    'auto-translated to': '已自动翻译为',
    'auto translation failed': '自动翻译失败',
    'image size must be less than 5mb': '图片大小必须小于 5MB',
    'image uploaded successfully': '图片上传成功',
    'failed to upload image': '图片上传失败',
    'maximum 10 tags allowed': '最多允许 10 个标签',
    'title is required': '标题为必填项',
    'title must be less than 200 characters': '标题必须少于 200 个字符',
    'please select a category': '请选择分类',
    'excerpt must be less than 500 characters': '摘要必须少于 500 个字符',
    'news content is required': '新闻内容为必填项',
    'draft saved successfully': '草稿保存成功',
    'news submitted for review': '新闻已提交审核',
    'failed to save news': '保存新闻失败',
    'failed to generate preview': '生成预览失败',
    'select translation language': '选择翻译语言',
    'translation title is required': '翻译标题为必填项',
    'news content is required for translation': '翻译需要新闻内容',
    'failed to prepare translation content': '准备翻译内容失败',
    'edit news': '编辑新闻',
    'back': '返回',
    'create and publish amazing content': '创建并发布优质内容',
    'save draft': '保存草稿',
    'submit for review': '提交审核',
    'news title *': '新闻标题 *',
    'enter a compelling title...': '输入一个有吸引力的标题...',
    'characters': '字符',
    'featured image': '特色图片',
    'uploading image...': '正在上传图片...',
    'please wait while your image is being uploaded': '请稍候，正在上传你的图片',
    'upload a featured image for your news': '为你的新闻上传特色图片',
    'jpg, png or webp. max 5mb.': 'JPG、PNG 或 WEBP。最大 5MB。',
    'choose image': '选择图片',
    'news content *': '新闻内容 *',
    'use rich text formatting': '使用富文本格式',
    'failed to load news content. please refresh or try again.': '加载新闻内容失败。请刷新或重试。',
    'start writing your news...': '开始撰写你的新闻...',
    'tip: use "/" to see formatting options. drag blocks to reorder them.': '提示：输入“/”查看格式选项，拖动区块可重新排序。',
    'translation content': '翻译内容',
    'no translation yet': '暂无翻译',
    'target language': '目标语言',
    'translated title': '已翻译标题',
    'translated excerpt': '已翻译摘要',
    'auto translate': '自动翻译',
    'save translation': '保存翻译',
    'write translated content in': '以以下语言撰写翻译内容',
    'excerpt': '摘要',
    'brief description of your news (shown in previews)': '新闻简要描述（用于预览显示）',
    'category *': '分类 *',
    'no categories available. ask an admin to create some.': '暂无可用分类。请让管理员先创建分类。',
    'tags': '标签',
    'add a tag...': '添加标签...',
    'add': '添加',
    'press enter or click add to add tags': '按 Enter 或点击添加来加入标签',
    'news options': '新闻选项',
    'publishing info': '发布信息',
    'created': '创建时间',
    'review': '审核中',
    'in_progress': '进行中',
    'all posts': '全部内容',
    'my posts': '我的内容',
    'total posts': '内容总数',
    'new post': '新内容',
    'post insights': '内容洞察',
    'recent posts': '最新内容',
    'no recent posts': '暂无最新内容',
    'no top posts yet': '暂无热门内容',
    'write new post': '创建新内容',
    'view my posts': '查看我的内容',
    'review pending posts': '审核待处理内容',
    'review and manage every post across the newsroom.': '审核并管理编辑部中的全部内容。',
    'view post': '查看内容',
    'posts': '内容',
    'no posts found': '未找到内容',
    'no posts yet': '暂无内容',
    'try adjusting your filters or create the first post.': '请调整筛选条件，或创建第一条内容。',
    'start writing your first post.': '开始创建你的第一条内容。',
    'delete post': '删除内容',
    'are you sure you want to delete this post? this action cannot be undone.': '确定要删除这条内容吗？此操作不可撤销。',
    'pending posts': '待审核内容',
    'posts awaiting your approval': '等待你审核的内容',
    'no posts pending review': '暂无待审核内容',
    'approve post': '批准内容',
    'are you sure you want to approve this post for publication?': '确定要批准这条内容发布吗？',
    'reject post': '拒绝内容',
    'post type': '内容类型',
    'post type *': '内容类型 *',
    'post title': '内容标题',
    'post title *': '内容标题 *',
    'post content': '内容正文',
    'post content *': '内容正文 *',
    'post content (optional for video)': '内容正文（视频可选）',
    'post options': '内容选项',
    'featured post': '精选内容',
    'breaking post': '突发内容',
    'mark as breaking content': '标记为突发内容',
    'brief description of your post (shown in previews)': '内容简要描述（用于预览显示）',
    'start writing your post...': '开始撰写你的内容...',
    'failed to load post content. please refresh or try again.': '加载内容失败，请刷新或重试。',
    'post submitted for review': '内容已提交审核',
    'failed to save post': '保存内容失败',
    'source post content is required before translation': '翻译前需要原始内容',
    'post content is required': '内容为必填项',
    'post content is required for translation': '翻译需要内容正文',
    'publish': '发布',
    'facebook url': 'Facebook 链接',
    'facebook url *': 'Facebook 链接 *',
    'facebook post': 'Facebook 帖子',
    'facebook video': 'Facebook 视频',
    'facebook reel': 'Facebook Reel',
    'facebook posts, videos, and reels in one place': 'Facebook 帖子、视频和 Reel 集中在一处',
    'video preview': '视频预览',
    'open on facebook': '在 Facebook 打开',
    'view on facebook': '在 Facebook 查看',
    'paste a public facebook video, reel, or post link': '粘贴公开的 Facebook 视频、Reel 或帖子链接',
    'use a valid facebook link (post/video/reel)': '请输入有效的 Facebook 链接（帖子/视频/Reel）',
    'this video cannot be embedded right now.': '此视频暂时无法嵌入。',
    'valid facebook video url is required for video posts': '视频内容需要有效的 Facebook 链接',
    'optional caption or context for this video post': '可选：为该视频内容添加说明或背景',
    'optional caption, context, or transcript...': '可选：填写说明、背景或字幕文本...',
    'if left empty, excerpt/title will be used as fallback content automatically.': '若留空，系统将自动使用摘要/标题作为兜底内容。',
    'required fields': '必填字段',
    'completed': '已完成',
    'select type first. required fields update automatically.': '请先选择类型，必填字段会自动更新。',
    'all types': '全部类型',
    'video posts': '视频内容',
    'video': '视频',
    'videos': '视频',
    'latest videos': '最新视频',
    'manage facebook post, video, and reel links in one place. homepage video sections read from this list.': '在一个地方统一管理 Facebook 帖子、视频和 Reel 链接。首页视频版块将读取此列表。',
    'no facebook videos configured yet. add links in the video posts dashboard page.': '尚未配置 Facebook 视频。请在 Video Posts 管理页添加链接。',
    'unsaved changes': '有未保存的更改',
    'add video': '添加视频',
    'enabled': '已启用',
    'valid links': '有效链接',
    'duplicates': '重复项',
    'video list': '视频列表',
    'paste facebook links only. reorder items to control appearance.': '仅粘贴 Facebook 链接。可通过排序控制展示顺序。',
    'no video posts yet': '暂无视频内容',
    'add first video post': '添加第一条视频内容',
    'duplicate': '重复',
    'ready': '就绪',
    'invalid': '无效',
    'move up': '上移',
    'move down': '下移',
    'headline': '标题',
    'video headline': '视频标题',
    'published date (optional)': '发布日期（可选）',
    'display style': '显示样式',
    'auto (detect from facebook link)': '自动（从 Facebook 链接识别）',
    'landscape (16:9)': '横版 (16:9)',
    'reel (9:16)': 'Reel (9:16)',
    'facebook link (post/video/reel)': 'Facebook 链接（帖子/视频/Reel）',
    'invalid facebook url': '无效的 Facebook 链接',
    'duplicate facebook url': '重复的 Facebook 链接',
    'short description': '简短描述',
    'select a category': '选择分类',
    'please upload an image file': '请上传图片文件',
    'upload a featured image for your post': '为你的内容上传特色图片',
    'show in featured section': '显示在精选版块',
    'mark as machine translated': '标记为机器翻译',
    'remove video post': '移除视频内容',
    'are you sure you want to remove this video post?': '确定要移除这条视频内容吗？',
    'remove': '移除',
    'invalid facebook links at row(s)': '以下行的 Facebook 链接无效',
    'duplicate facebook links at row(s)': '以下行存在重复的 Facebook 链接',
    'save': '保存',
  },
};

function normalizePhrase(value) {
  return String(value || '').trim().replace(/\s+/g, ' ').toLowerCase();
}

function interpolate(template, values) {
  if (!values || typeof values !== 'object') return template;
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{{${key}}}`, String(value)),
    template
  );
}

function translatePhrase(language, value) {
  if (typeof value !== 'string' || !value.trim()) return value;
  const map = PHRASE_TRANSLATIONS[language];
  if (!map) return value;
  const normalized = normalizePhrase(value);
  const translated = map[normalized];
  if (!translated) return value;

  const leading = value.match(/^\s*/)?.[0] || '';
  const trailing = value.match(/\s*$/)?.[0] || '';
  return `${leading}${translated}${trailing}`;
}

function normalizeLanguage(value) {
  const code = String(value || '').trim().toLowerCase();
  if (SUPPORTED_LANGUAGES.includes(code)) {
    return code;
  }
  if (code.startsWith('zh')) return 'zh';
  if (code.startsWith('km')) return 'km';
  return DEFAULT_LANGUAGE;
}

function getInitialLanguage() {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
  const fromStorage = localStorage.getItem('preferredLanguage') || localStorage.getItem('i18nextLng');
  if (fromStorage) return normalizeLanguage(fromStorage);
  return normalizeLanguage(navigator.language);
}

if (typeof window !== 'undefined') {
  SHARED_LANGUAGE = getInitialLanguage();
  applyDocumentLanguage(SHARED_LANGUAGE);
}

function applyDocumentLanguage(language) {
  if (typeof document !== 'undefined') {
    document.documentElement.lang = language;
    document.documentElement.dir = 'ltr';
  }
}

function publishLanguage(value) {
  const nextLanguage = normalizeLanguage(value);
  if (nextLanguage === SHARED_LANGUAGE) return nextLanguage;
  SHARED_LANGUAGE = nextLanguage;
  applyDocumentLanguage(nextLanguage);
  for (const notify of LANGUAGE_SUBSCRIBERS) {
    try {
      notify(nextLanguage);
    } catch {
      // no-op; keep other subscribers alive
    }
  }
  return nextLanguage;
}

function dispatchLanguageChangeEvents(language) {
  if (typeof window === 'undefined') return;
  try {
    window.dispatchEvent(new CustomEvent(APP_LANGUAGE_CHANGE_EVENT, { detail: { language } }));
  } catch {
    if (typeof document !== 'undefined' && document.createEvent) {
      const event = document.createEvent('CustomEvent');
      event.initCustomEvent(APP_LANGUAGE_CHANGE_EVENT, false, false, { language });
      window.dispatchEvent(event);
    }
  }
  window.dispatchEvent(new Event(LANGUAGE_CHANGE_FALLBACK_EVENT));
}

export function setPreferredLanguage(value) {
  const nextLanguage = normalizeLanguage(value);
  const publishedLanguage = publishLanguage(nextLanguage);

  if (typeof window !== 'undefined') {
    localStorage.setItem('i18nextLng', publishedLanguage);
    localStorage.setItem('preferredLanguage', publishedLanguage);
  }

  dispatchLanguageChangeEvents(publishedLanguage);
  return publishedLanguage;
}

export function translateCurrentText(value = '') {
  return translatePhrase(SHARED_LANGUAGE, value);
}

function subscribeLanguage(listener) {
  LANGUAGE_SUBSCRIBERS.add(listener);
  return () => {
    LANGUAGE_SUBSCRIBERS.delete(listener);
  };
}

function getLanguageSnapshot() {
  return SHARED_LANGUAGE;
}

function bindLanguageListeners() {
  if (LANGUAGE_LISTENERS_BOUND || typeof window === 'undefined') return;
  LANGUAGE_LISTENERS_BOUND = true;

  const onStorage = (event) => {
    if (event.key !== 'i18nextLng' && event.key !== 'preferredLanguage') return;
    publishLanguage(event.newValue || DEFAULT_LANGUAGE);
  };

  const onLanguageChange = (event) => {
    publishLanguage(event?.detail?.language || DEFAULT_LANGUAGE);
  };

  const syncFromStorage = () => {
    publishLanguage(getInitialLanguage());
  };

  const onVisibilityChange = () => {
    if (document.visibilityState === 'visible') {
      syncFromStorage();
    }
  };

  window.addEventListener('storage', onStorage);
  window.addEventListener(APP_LANGUAGE_CHANGE_EVENT, onLanguageChange);
  window.addEventListener(LANGUAGE_CHANGE_FALLBACK_EVENT, syncFromStorage);
  window.addEventListener('focus', syncFromStorage);
  document.addEventListener('visibilitychange', onVisibilityChange);
}

function translate(language, key, fallback = '') {
  const dictionary = TRANSLATIONS[language] || TRANSLATIONS[DEFAULT_LANGUAGE];
  const resolved = dictionary[key] || fallback || key;
  return translatePhrase(language, resolved);
}

export function useLanguage() {
  bindLanguageListeners();
  const language = useSyncExternalStore(subscribeLanguage, getLanguageSnapshot, getLanguageSnapshot);

  const t = useMemo(() => {
    return (key, fallback = '', values = null) => interpolate(translate(language, key, fallback), values);
  }, [language]);

  const translateText = useMemo(() => {
    return (value = '') => translatePhrase(language, value);
  }, [language]);

  return {
    language,
    t,
    translateText,
  };
}

export default useLanguage;
